version: "3.5"
services:
  nina:
    build:
      context: .
      args:
        APP_HOME: "${PWD}"
    image: nina-dev:latest
    volumes:
      - ./src:${PWD}/src
      - ./test:${PWD}/test
      - ./resources:${PWD}/resources
      - m2:/usr/local/lib/m2
      - ./log:${PWD}/log
    ports:
      - 4888:5888
      - 8001:80
    depends_on:
      - ldap

  ldap:
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: Nina
      LDAP_DOMAIN: thetripps.org
      LDAP_ADMIN_PASSWORD: "omelet-sever-exposure-averse"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-conf:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636

  admin:
    image: osixia/phpldapadmin:0.7.2
    depends_on:
      - ldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - 6443:443
      - 6080:80
    volumes:
      - ./config/php_admin.yml:/container/environment/01-custom/env.yaml

volumes:
  m2:
  ldap-data:
  ldap-conf:
